config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :countries
  resources :tpe_updates
  resources :teams do
    member do
      post 'get_lines_update'
    end
  end
  resources :skaters do
    member do
      post 'get_tpa_updates'
    end
  end
  resources :skater_stats
  resources :positions
  resources :leagues
  resources :goalies do
    member do
      post 'get_tpa_updates'
    end
  end
  resources :goalie_stats
  resources :draft_seasons
  devise_for :users

  post 'league/data_update', to: 'leagues#update_data', as: :update_data

  root 'leagues#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :skaters
  has_many :goalies
end

app/models/draft_season.rb
class DraftSeason < ApplicationRecord
end

app/models/goalie.rb
class Goalie < ApplicationRecord
  belongs_to :position, required: false
  belongs_to :team, required: false
  belongs_to :draft_season, required: false
  belongs_to :goalie_stat, required: false
  belongs_to :country, required: false
  has_many :goalie_tpe_updates, -> { order(week_ending: :desc)}
end

app/models/goalie_stat.rb
class GoalieStat < ApplicationRecord
end

app/models/goalie_tpe_update.rb
class GoalieTpeUpdate < ApplicationRecord
  belongs_to :goalie
end

app/models/last_update.rb
class LastUpdate < ApplicationRecord
end

app/models/league.rb
class League < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :teams
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/skater.rb
class Skater < ApplicationRecord
  belongs_to :position, required: false
  belongs_to :team, required: false
  belongs_to :draft_season, required: false
  belongs_to :skater_stat, required: false
  belongs_to :country, required: false
  has_many :skater_tpe_updates, -> { order(week_ending: :desc)}
end

app/models/skater_stat.rb
class SkaterStat < ApplicationRecord
end

app/models/skater_tpe_update.rb
class SkaterTpeUpdate < ApplicationRecord
  belongs_to :skater
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  belongs_to :league
  has_many :skaters, -> { order(position_id: :asc, tpa: :desc) }
  has_many :goalies, -> { order(tpa: :desc) }
  has_many :skater_stats, through: :skaters
  has_many :goalie_stats, through: :goalies
  has_many :five_vs_five_forwards, -> { order(line_number: :asc) }
  has_many :five_vs_five_defenses, -> { order(line_number: :asc) }
  has_many :four_vs_four_forwards, -> { order(line_number: :asc) }
  has_many :four_vs_four_defenses, -> { order(line_number: :asc) }
  has_many :last_minute_attacks
  has_many :last_minute_defends
  has_many :penalty_kill_four_players_forwards, -> { order(line_number: :asc) }
  has_many :penalty_kill_four_players_defenses, -> { order(line_number: :asc) }
  has_many :penalty_kill_three_players, -> { order(line_number: :asc) }
  has_many :power_play_forwards, -> { order(line_number: :asc) }
  has_many :power_play_defenses, -> { order(line_number: :asc) }


  def centers
    skaters.where(position_id: 1)
  end

  def center_total_tpa
    centers.sum(:tpa)
  end

  def center_avg_tpa
    (center_total_tpa / centers.count) unless centers.count == 0
  end

  def left_wingers
    skaters.where(position_id: 2)
  end

  def left_wingers_total_tpa
    left_wingers.sum(:tpa)
  end

  def left_wingers_avg_tpa
    (left_wingers_total_tpa / left_wingers.count) unless left_wingers.count == 0
  end

  def right_wingers
    skaters.where(position_id: 3)
  end

  def right_wingers_total_tpa
    right_wingers.sum(:tpa)
  end

  def right_wingers_avg_tpa
    (right_wingers_total_tpa / right_wingers.count) unless right_wingers.count == 0
  end

  def defenders
    skaters.where(position_id: 4)
  end

  def defenders_total_tpa
    defenders.sum(:tpa)
  end

  def defenders_avg_tpa
    (defenders_total_tpa / defenders.count) unless defenders.count == 0
  end

  def total_team_tpa
    total_skater_tpa + total_goalie_tpa
  end

  def avg_tpa
    (total_tpa / skaters.count + goalies.count) unless skaters.count == 0 or goalies.count == 0
  end

  def total_skater_tpa
    skater_stats.sum(:tpa)
  end

  def total_forward_tpa
    tpa = 0
    skaters.where(position_id: [1..3]).each do |skater|
      tpa += skater.skater_stat.tpa
    end
    tpa
  end

  def avg_forward_tpa
    (total_forward_tpa / skaters.where(position_id: [1..3]).count) unless skaters.where(position_id: [1..3]).count == 0
  end

  def total_defender_tpa
    tpa = 0
    skaters.where(position_id: 4).each do |skater|
      tpa += skater.skater_stat.tpa
    end
    tpa
  end

  def avg_defender_tpa
    (total_defender_tpa / skaters.where(position_id: 4).count) unless skaters.where(position_id: 4).count == 0
  end

  def total_goalie_tpa
    goalie_stats.sum(:tpa)
  end

  def avg_goalie_tpa
    (goalie_stats.sum(:tpa) / goalie_stats.count) unless goalie_stats.count == 0
  end
end

app/models/tpe_update.rb
class TpeUpdate < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/goalies_controller.rb
class GoaliesController < ApplicationController
  before_action :set_goalie, only: [:show, :edit, :update, :destroy, :get_tpa_updates]

  # GET /goalies
  # GET /goalies.json
  def index
    @goalies = Goalie.all
  end

  # GET /goalies/1
  # GET /goalies/1.json
  def show
    @goalie_stat = @goalie.goalie_stat
  end

  # GET /goalies/new
  def new
    @goalie = Goalie.new
  end

  # GET /goalies/1/edit
  def edit
  end

  # POST /goalies
  # POST /goalies.json
  def create
    @goalie = goalie.new(goalie_params)

    respond_to do |format|
      if @goalie.save
        format.html { redirect_to @goalie, notice: 'goalie was successfully created.' }
        format.json { render :show, status: :created, location: @goalie }
      else
        format.html { render :new }
        format.json { render json: @goalie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goalies/1
  # PATCH/PUT /goalies/1.json
  def update
    respond_to do |format|
      if @goalie.update(goalie_params)
        format.html { redirect_to @goalie, notice: 'goalie was successfully updated.' }
        format.json { render :show, status: :ok, location: @goalie }
      else
        format.html { render :edit }
        format.json { render json: @goalie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goalies/1
  # DELETE /goalies/1.json
  def destroy
    @goalie.destroy
    respond_to do |format|
      format.html { redirect_to goalies_url, notice: 'goalie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_tpa_updates
    GoalieTpaRetrivalWorker.perform_async @goalie.id
    redirect_to @goalie
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goalie
      @goalie = Goalie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goalie_params
      params.require(:goalie).permit(:name, :href, :position_id, :team_id, :draft_season_id, :goalie_stat_id)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/goalies_helper.rb
module GoaliesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/skaters_helper.rb
module SkatersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/goalies/_form.html.erb
<%= form_with(model: goalie, local: true) do |form| %>
  <% if goalie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goalie.errors.count, "error") %> prohibited this goalie from being saved:</h2>

      <ul>
      <% goalie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :href %>
    <%= form.text_field :href %>
  </div>

  <div class="field">
    <%= form.label :position_id %>
    <%= form.text_field :position_id %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.text_field :team_id %>
  </div>

  <div class="field">
    <%= form.label :draft_season_id %>
    <%= form.text_field :draft_season_id %>
  </div>

  <div class="field">
    <%= form.label :goalie_stat_id %>
    <%= form.text_field :goalie_stat_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goalies/edit.html.erb
<h1>Editing goalie</h1>

<%= render 'form', goalie: @goalie %>

<%= link_to 'Show', @goalie %> |
<%= link_to 'Back', goalies_path %>

app/views/goalies/index.html.erb
<h1>Goalies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Href</th>
      <th>Position</th>
      <th>Team</th>
      <th>Draft season</th>
      <th>Goalie stat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goalies.each do |goalie| %>
      <tr>
        <td><%= goalie.name %></td>
        <td><%= goalie.href %></td>
        <td><%= goalie.position %></td>
        <td><%= goalie.team %></td>
        <td><%= goalie.draft_season %></td>
        <td><%= goalie.goalie_stat %></td>
        <td><%= link_to 'Show', goalie %></td>
        <td><%= link_to 'Edit', edit_goalie_path(goalie) %></td>
        <td><%= link_to 'Destroy', goalie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New goalie', new_goalie_path %>

app/views/goalies/new.html.erb
<h1>New goalie</h1>

<%= render 'form', goalie: @goalie %>

<%= link_to 'Back', goalies_path %>

app/views/goalies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @goalie.name %>
</p>

<p>
  <strong>Href:</strong>
  <%= @goalie.href %>
</p>

<p>
  <strong>Position:</strong>
  <%= link_to @goalie.position.name, @goalie.position %>
</p>

<p>
  <strong>Team:</strong>
  <%= link_to @goalie.team.name, @goalie.team %>
</p>

<p>
  <strong>Draft season:</strong>
  <%= link_to @goalie.draft_season.name, @goalie.draft_season %>
</p>

<p>
  <strong>Country:</strong>
  <%= link_to @goalie.country.try(:name), @goalie.country %>
</p>

<p>
  <strong>Height:</strong>
  <%= @goalie.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @goalie.weight %>
</p>

<p>
  <strong>Age:</strong>
  <%= @goalie.age %>
</p>

<p>
  <strong>Goalie stat:</strong>
  <%= link_to 'Stats', @goalie.goalie_stat %>
</p>

<%= link_to 'Update Goalie Data', get_tpa_updates_goalie_path(@goalie), method: :post, class: 'btn btn-primary' %>

<p>
  <strong>Sk:</strong>
  <%= @goalie_stat.sk %>
</p>

<p>
  <strong>Sz:</strong>
  <%= @goalie_stat.sz %>
</p>

<p>
  <strong>Ag:</strong>
  <%= @goalie_stat.ag %>
</p>

<p>
  <strong>Rb:</strong>
  <%= @goalie_stat.rb %>
</p>

<p>
  <strong>Sc:</strong>
  <%= @goalie_stat.sc %>
</p>

<p>
  <strong>Hs:</strong>
  <%= @goalie_stat.hs %>
</p>

<p>
  <strong>Rt:</strong>
  <%= @goalie_stat.rt %>
</p>

<p>
  <strong>Ph:</strong>
  <%= @goalie_stat.ph %>
</p>

<p>
  <strong>Ps:</strong>
  <%= @goalie_stat.ps %>
</p>

<p>
  <strong>Ex:</strong>
  <%= @goalie_stat.ex %>
</p>

<p>
  <strong>Ld:</strong>
  <%= @goalie_stat.ld %>
</p>

<p>
  <strong>Tpa:</strong>
  <%= @goalie_stat.tpa %>
</p>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Week Ending</th>
    <th scope="col">TPE</th>
  </tr>
  </thead>
  <tbody>
  <% @goalie.goalie_tpe_updates.each do |tpe| %>
    <tr>
      <td><%= tpe.week_ending %></td>
      <td><%= tpe.tpe%></td>
    </tr>
  <% end%>
  </tbody>
</table>

<%= link_to 'Edit', edit_goalie_path(@goalie) %> |
<%= link_to 'Back', goalies_path %>