config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :countries
  resources :tpe_updates
  resources :teams do
    member do
      post 'get_lines_update'
    end
  end
  resources :skaters do
    member do
      post 'get_tpa_updates'
    end
  end
  resources :skater_stats
  resources :positions
  resources :leagues
  resources :goalies do
    member do
      post 'get_tpa_updates'
    end
  end
  resources :goalie_stats
  resources :draft_seasons
  devise_for :users

  post 'league/data_update', to: 'leagues#update_data', as: :update_data

  root 'leagues#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :skaters
  has_many :goalies
end

app/models/draft_season.rb
class DraftSeason < ApplicationRecord
end

app/models/goalie.rb
class Goalie < ApplicationRecord
  belongs_to :position, required: false
  belongs_to :team, required: false
  belongs_to :draft_season, required: false
  belongs_to :goalie_stat, required: false
  belongs_to :country, required: false
  has_many :goalie_tpe_updates, -> { order(week_ending: :desc)}
end

app/models/goalie_stat.rb
class GoalieStat < ApplicationRecord
end

app/models/goalie_tpe_update.rb
class GoalieTpeUpdate < ApplicationRecord
  belongs_to :goalie
end

app/models/last_minute_attack.rb
class LastMinuteAttack < ApplicationRecord
  belongs_to :team
  belongs_to :left_wing, class_name: :Skater, foreign_key: :left_wing_id, optional: true
  belongs_to :center, class_name: :Skater, foreign_key: :center_id, optional: true
  belongs_to :right_wing, class_name: :Skater, foreign_key: :right_wing_id, optional: true
  belongs_to :left_defense, class_name: :Skater, foreign_key: :left_defense_id, optional: true
  belongs_to :right_defense, class_name: :Skater, foreign_key: :right_defense_id, optional: true
end

app/models/last_update.rb
class LastUpdate < ApplicationRecord
end

app/models/league.rb
class League < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :teams
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/skater.rb
class Skater < ApplicationRecord
  belongs_to :position, required: false
  belongs_to :team, required: false
  belongs_to :draft_season, required: false
  belongs_to :skater_stat, required: false
  belongs_to :country, required: false
  has_many :skater_tpe_updates, -> { order(week_ending: :desc)}
end

app/models/skater_stat.rb
class SkaterStat < ApplicationRecord
end

app/models/skater_tpe_update.rb
class SkaterTpeUpdate < ApplicationRecord
  belongs_to :skater
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  belongs_to :league
  has_many :skaters, -> { order(position_id: :asc, tpa: :desc) }
  has_many :goalies, -> { order(tpa: :desc) }
  has_many :skater_stats, through: :skaters
  has_many :goalie_stats, through: :goalies
  has_many :five_vs_five_forwards, -> { order(line_number: :asc) }
  has_many :five_vs_five_defenses, -> { order(line_number: :asc) }
  has_many :four_vs_four_forwards, -> { order(line_number: :asc) }
  has_many :four_vs_four_defenses, -> { order(line_number: :asc) }
  has_many :last_minute_attacks
  has_many :last_minute_defends
  has_many :penalty_kill_four_players_forwards, -> { order(line_number: :asc) }
  has_many :penalty_kill_four_players_defenses, -> { order(line_number: :asc) }
  has_many :penalty_kill_three_players, -> { order(line_number: :asc) }
  has_many :power_play_forwards, -> { order(line_number: :asc) }
  has_many :power_play_defenses, -> { order(line_number: :asc) }


  def centers
    skaters.where(position_id: 1)
  end

  def center_total_tpa
    centers.sum(:tpa)
  end

  def center_avg_tpa
    (center_total_tpa / centers.count) unless centers.count == 0
  end

  def left_wingers
    skaters.where(position_id: 2)
  end

  def left_wingers_total_tpa
    left_wingers.sum(:tpa)
  end

  def left_wingers_avg_tpa
    (left_wingers_total_tpa / left_wingers.count) unless left_wingers.count == 0
  end

  def right_wingers
    skaters.where(position_id: 3)
  end

  def right_wingers_total_tpa
    right_wingers.sum(:tpa)
  end

  def right_wingers_avg_tpa
    (right_wingers_total_tpa / right_wingers.count) unless right_wingers.count == 0
  end

  def defenders
    skaters.where(position_id: 4)
  end

  def defenders_total_tpa
    defenders.sum(:tpa)
  end

  def defenders_avg_tpa
    (defenders_total_tpa / defenders.count) unless defenders.count == 0
  end

  def total_team_tpa
    total_skater_tpa + total_goalie_tpa
  end

  def avg_tpa
    (total_tpa / skaters.count + goalies.count) unless skaters.count == 0 or goalies.count == 0
  end

  def total_skater_tpa
    skater_stats.sum(:tpa)
  end

  def total_forward_tpa
    tpa = 0
    skaters.where(position_id: [1..3]).each do |skater|
      tpa += skater.skater_stat.tpa
    end
    tpa
  end

  def avg_forward_tpa
    (total_forward_tpa / skaters.where(position_id: [1..3]).count) unless skaters.where(position_id: [1..3]).count == 0
  end

  def total_defender_tpa
    tpa = 0
    skaters.where(position_id: 4).each do |skater|
      tpa += skater.skater_stat.tpa
    end
    tpa
  end

  def avg_defender_tpa
    (total_defender_tpa / skaters.where(position_id: 4).count) unless skaters.where(position_id: 4).count == 0
  end

  def total_goalie_tpa
    goalie_stats.sum(:tpa)
  end

  def avg_goalie_tpa
    (goalie_stats.sum(:tpa) / goalie_stats.count) unless goalie_stats.count == 0
  end
end

app/models/tpe_update.rb
class TpeUpdate < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :abbr)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/goalies_helper.rb
module GoaliesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/skaters_helper.rb
module SkatersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :abbr %>
    <%= form.text_field :abbr %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.abbr %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>Abbr:</strong>
  <%= @country.abbr %>
</p>

Skaters
<div class="table-responsive">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Position</th>
      <th scope="col">TPE</th>
    </tr>
    </thead>
    <tbody>
    <% @country.skaters.each do |skater| %>
      <tr>
        <th><%= skater.name %></th>
        <th><%= skater.position.name %></th>
        <th><%= skater.tpa %></th>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

Goalies
<div class="table-responsive">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Position</th>
      <th scope="col">TPE</th>
    </tr>
    </thead>
    <tbody>
    <% @country.goalies.each do |skater| %>
      <tr>
        <th><%= skater.name %></th>
        <th><%= skater.position.name %></th>
        <th><%= skater.tpa %></th>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>