config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :countries
  resources :tpe_updates
  resources :teams do
    member do
      post 'get_lines_update'
    end
  end
  resources :skaters do
    member do
      post 'get_tpa_updates'
    end
  end
  resources :skater_stats
  resources :positions
  resources :leagues
  resources :goalies do
    member do
      post 'get_tpa_updates'
    end
  end
  resources :goalie_stats
  resources :draft_seasons
  devise_for :users

  post 'league/data_update', to: 'leagues#update_data', as: :update_data

  root 'leagues#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :skaters
  has_many :goalies
end

app/models/draft_season.rb
class DraftSeason < ApplicationRecord
end

app/models/goalie.rb
class Goalie < ApplicationRecord
  belongs_to :position, required: false
  belongs_to :team, required: false
  belongs_to :draft_season, required: false
  belongs_to :goalie_stat, required: false
  belongs_to :country, required: false
  has_many :goalie_tpe_updates, -> { order(week_ending: :desc)}
end

app/models/goalie_stat.rb
class GoalieStat < ApplicationRecord
end

app/models/goalie_tpe_update.rb
class GoalieTpeUpdate < ApplicationRecord
  belongs_to :goalie
end

app/models/last_update.rb
class LastUpdate < ApplicationRecord
end

app/models/league.rb
class League < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :teams
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/skater.rb
class Skater < ApplicationRecord
  belongs_to :position, required: false
  belongs_to :team, required: false
  belongs_to :draft_season, required: false
  belongs_to :skater_stat, required: false
  belongs_to :country, required: false
  has_many :skater_tpe_updates, -> { order(week_ending: :desc)}
end

app/models/skater_stat.rb
class SkaterStat < ApplicationRecord
end

app/models/skater_tpe_update.rb
class SkaterTpeUpdate < ApplicationRecord
  belongs_to :skater
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  belongs_to :league
  has_many :skaters, -> { order(position_id: :asc, tpa: :desc) }
  has_many :goalies, -> { order(tpa: :desc) }
  has_many :skater_stats, through: :skaters
  has_many :goalie_stats, through: :goalies
  has_many :five_vs_five_forwards, -> { order(line_number: :asc) }
  has_many :five_vs_five_defenses, -> { order(line_number: :asc) }
  has_many :four_vs_four_forwards, -> { order(line_number: :asc) }
  has_many :four_vs_four_defenses, -> { order(line_number: :asc) }
  has_many :last_minute_attacks
  has_many :last_minute_defends
  has_many :penalty_kill_four_players_forwards, -> { order(line_number: :asc) }
  has_many :penalty_kill_four_players_defenses, -> { order(line_number: :asc) }
  has_many :penalty_kill_three_players, -> { order(line_number: :asc) }
  has_many :power_play_forwards, -> { order(line_number: :asc) }
  has_many :power_play_defenses, -> { order(line_number: :asc) }


  def centers
    skaters.where(position_id: 1)
  end

  def center_total_tpa
    centers.sum(:tpa)
  end

  def center_avg_tpa
    (center_total_tpa / centers.count) unless centers.count == 0
  end

  def left_wingers
    skaters.where(position_id: 2)
  end

  def left_wingers_total_tpa
    left_wingers.sum(:tpa)
  end

  def left_wingers_avg_tpa
    (left_wingers_total_tpa / left_wingers.count) unless left_wingers.count == 0
  end

  def right_wingers
    skaters.where(position_id: 3)
  end

  def right_wingers_total_tpa
    right_wingers.sum(:tpa)
  end

  def right_wingers_avg_tpa
    (right_wingers_total_tpa / right_wingers.count) unless right_wingers.count == 0
  end

  def defenders
    skaters.where(position_id: 4)
  end

  def defenders_total_tpa
    defenders.sum(:tpa)
  end

  def defenders_avg_tpa
    (defenders_total_tpa / defenders.count) unless defenders.count == 0
  end

  def total_team_tpa
    total_skater_tpa + total_goalie_tpa
  end

  def avg_tpa
    (total_tpa / skaters.count + goalies.count) unless skaters.count == 0 or goalies.count == 0
  end

  def total_skater_tpa
    skater_stats.sum(:tpa)
  end

  def total_forward_tpa
    tpa = 0
    skaters.where(position_id: [1..3]).each do |skater|
      tpa += skater.skater_stat.tpa
    end
    tpa
  end

  def avg_forward_tpa
    (total_forward_tpa / skaters.where(position_id: [1..3]).count) unless skaters.where(position_id: [1..3]).count == 0
  end

  def total_defender_tpa
    tpa = 0
    skaters.where(position_id: 4).each do |skater|
      tpa += skater.skater_stat.tpa
    end
    tpa
  end

  def avg_defender_tpa
    (total_defender_tpa / skaters.where(position_id: 4).count) unless skaters.where(position_id: 4).count == 0
  end

  def total_goalie_tpa
    goalie_stats.sum(:tpa)
  end

  def avg_goalie_tpa
    (goalie_stats.sum(:tpa) / goalie_stats.count) unless goalie_stats.count == 0
  end
end

app/models/tpe_update.rb
class TpeUpdate < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/goalie_stats_controller.rb
class GoalieStatsController < ApplicationController
  before_action :set_goalie_stat, only: [:show, :edit, :update, :destroy]

  # GET /goalie_stats
  # GET /goalie_stats.json
  def index
    @goalie_stats = GoalieStat.all
  end

  # GET /goalie_stats/1
  # GET /goalie_stats/1.json
  def show
  end

  # GET /goalie_stats/new
  def new
    @goalie_stat = GoalieStat.new
  end

  # GET /goalie_stats/1/edit
  def edit
  end

  # POST /goalie_stats
  # POST /goalie_stats.json
  def create
    @goalie_stat = GoalieStat.new(goalie_stat_params)

    respond_to do |format|
      if @goalie_stat.save
        format.html { redirect_to @goalie_stat, notice: 'Goalie stat was successfully created.' }
        format.json { render :show, status: :created, location: @goalie_stat }
      else
        format.html { render :new }
        format.json { render json: @goalie_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goalie_stats/1
  # PATCH/PUT /goalie_stats/1.json
  def update
    respond_to do |format|
      if @goalie_stat.update(goalie_stat_params)
        format.html { redirect_to @goalie_stat, notice: 'Goalie stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @goalie_stat }
      else
        format.html { render :edit }
        format.json { render json: @goalie_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goalie_stats/1
  # DELETE /goalie_stats/1.json
  def destroy
    @goalie_stat.destroy
    respond_to do |format|
      format.html { redirect_to goalie_stats_url, notice: 'Goalie stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goalie_stat
      @goalie_stat = GoalieStat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goalie_stat_params
      params.require(:goalie_stat).permit(:sk, :sz, :ag, :rb, :sc, :hs, :rt, :ph, :ps, :ex, :ld, :tpa)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/goalie_stats_helper.rb
module GoalieStatsHelper
end

app/helpers/goalies_helper.rb
module GoaliesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/skaters_helper.rb
module SkatersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/goalie_stats/_form.html.erb
<%= form_with(model: goalie_stat, local: true) do |form| %>
  <% if goalie_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goalie_stat.errors.count, "error") %> prohibited this goalie_stat from being saved:</h2>

      <ul>
      <% goalie_stat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sk %>
    <%= form.number_field :sk %>
  </div>

  <div class="field">
    <%= form.label :sz %>
    <%= form.number_field :sz %>
  </div>

  <div class="field">
    <%= form.label :ag %>
    <%= form.number_field :ag %>
  </div>

  <div class="field">
    <%= form.label :rb %>
    <%= form.number_field :rb %>
  </div>

  <div class="field">
    <%= form.label :sc %>
    <%= form.number_field :sc %>
  </div>

  <div class="field">
    <%= form.label :hs %>
    <%= form.number_field :hs %>
  </div>

  <div class="field">
    <%= form.label :rt %>
    <%= form.number_field :rt %>
  </div>

  <div class="field">
    <%= form.label :ph %>
    <%= form.number_field :ph %>
  </div>

  <div class="field">
    <%= form.label :ps %>
    <%= form.number_field :ps %>
  </div>

  <div class="field">
    <%= form.label :ex %>
    <%= form.number_field :ex %>
  </div>

  <div class="field">
    <%= form.label :ld %>
    <%= form.number_field :ld %>
  </div>

  <div class="field">
    <%= form.label :tpa %>
    <%= form.number_field :tpa %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goalie_stats/edit.html.erb
<h1>Editing Goalie Stat</h1>

<%= render 'form', goalie_stat: @goalie_stat %>

<%= link_to 'Show', @goalie_stat %> |
<%= link_to 'Back', goalie_stats_path %>

app/views/goalie_stats/index.html.erb
<h1>Goalie Stats</h1>

<table>
  <thead>
    <tr>
      <th>Sk</th>
      <th>Sz</th>
      <th>Ag</th>
      <th>Rb</th>
      <th>Sc</th>
      <th>Hs</th>
      <th>Rt</th>
      <th>Ph</th>
      <th>Ps</th>
      <th>Ex</th>
      <th>Ld</th>
      <th>Tpa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goalie_stats.each do |goalie_stat| %>
      <tr>
        <td><%= goalie_stat.sk %></td>
        <td><%= goalie_stat.sz %></td>
        <td><%= goalie_stat.ag %></td>
        <td><%= goalie_stat.rb %></td>
        <td><%= goalie_stat.sc %></td>
        <td><%= goalie_stat.hs %></td>
        <td><%= goalie_stat.rt %></td>
        <td><%= goalie_stat.ph %></td>
        <td><%= goalie_stat.ps %></td>
        <td><%= goalie_stat.ex %></td>
        <td><%= goalie_stat.ld %></td>
        <td><%= goalie_stat.tpa %></td>
        <td><%= link_to 'Show', goalie_stat %></td>
        <td><%= link_to 'Edit', edit_goalie_stat_path(goalie_stat) %></td>
        <td><%= link_to 'Destroy', goalie_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goalie Stat', new_goalie_stat_path %>

app/views/goalie_stats/new.html.erb
<h1>New Goalie Stat</h1>

<%= render 'form', goalie_stat: @goalie_stat %>

<%= link_to 'Back', goalie_stats_path %>

app/views/goalie_stats/show.html.erb
<p>
  <strong>Sk:</strong>
  <%= @goalie_stat.sk %>
</p>

<p>
  <strong>Sz:</strong>
  <%= @goalie_stat.sz %>
</p>

<p>
  <strong>Ag:</strong>
  <%= @goalie_stat.ag %>
</p>

<p>
  <strong>Rb:</strong>
  <%= @goalie_stat.rb %>
</p>

<p>
  <strong>Sc:</strong>
  <%= @goalie_stat.sc %>
</p>

<p>
  <strong>Hs:</strong>
  <%= @goalie_stat.hs %>
</p>

<p>
  <strong>Rt:</strong>
  <%= @goalie_stat.rt %>
</p>

<p>
  <strong>Ph:</strong>
  <%= @goalie_stat.ph %>
</p>

<p>
  <strong>Ps:</strong>
  <%= @goalie_stat.ps %>
</p>

<p>
  <strong>Ex:</strong>
  <%= @goalie_stat.ex %>
</p>

<p>
  <strong>Ld:</strong>
  <%= @goalie_stat.ld %>
</p>

<p>
  <strong>Tpa:</strong>
  <%= @goalie_stat.tpa %>
</p>

<%= link_to 'Edit', edit_goalie_stat_path(@goalie_stat) %> |
<%= link_to 'Back', goalie_stats_path %>